---
- name: Ensure apt cache is updated.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure correct kernel headers are installed.
  shell: "apt-get -y install linux-headers-$(uname -r)"
  tags: ['skip_ansible_lint']

# SSH daemon configuration.
- name: Configure SSH daemon.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^UseDNS'
      line: 'UseDNS no'
    - regexp: '^GSSAPIAuthentication'
      line: 'GSSAPIAuthentication no'

# Vagrant SSH configuration.
- name: Configure Vagrant .ssh directory.
  file:
    path: /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0700

- name: Get Vagrant's public key.
  get_url:
    url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: 0600

# VirtualBox tools installation.
- name: Check if VirtualBox is running the guest VM.
  stat: path=/home/vagrant/.vbox_version
  register: virtualbox_check

- include_tasks: virtualbox.yml
  when: virtualbox_check.stat.exists

# VMware tools installation.
- name: Check if VMWare is running the guest VM.
  shell: "dmesg | grep VMware | grep -v VMMouse | wc -l"
  changed_when: false
  failed_when: false
  register: vmware_check

- include_tasks: vmware.yml
  when: vmware_check.stdout | int > 0

# Cleanup tasks.
- name: Check if X-Desktop is defined
  register: xdesktop_defined
  ansible.builtin.set_fact:
    xdesktop_exists: "{{ xdesktop is defined }}"

- name: Check if X-Windows Desktop is running
  shell: "echo $XDG_CURRENT_DESKTOP"
  register: xdesktop
  when: xdesktop_exists == false

- name: Remove unneeded packages.
  apt:
    name:
      - ppp
      - pppconfig
      - pppoeconf
      - cpp
      - gcc
      - g++
      - linux-source    
      - libx11-data
      - xauth
      - libxmuu1
      - libxcb1
      - libx11-6
      - libxext6
    state: absent
  when: xdesktop | length == 0

- name: Remove unneeded packages (by regex).
  shell: "apt-get -y remove '.*-dev$'"
  tags: ['skip_ansible_lint']

- name: Clean up apt.
  command: "{{ item }}"
  changed_when: false
  with_items:
    - apt-get -y autoremove
    - apt-get -y clean
